#This is the only file that needs to be created on the cluster manually
# This would sync this github repo to the the cluster. 

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-argo
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

  project: default
  source:
    repoURL: https://github.com/technekey/sample-argo-example-repo.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
